spring:
  profiles:
    include: bampo
  application:
    name: bampo-spring
  datasource:
    url: ${env.SPRING_DATASOURCE_URL}
    username: ${env.SPRING_DATASOURCE_USERNAME}
    password: ${env.SPRING_DATASOURCE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: BampoHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        format_sql: true
  flyway:
    enabled: false
  mail:
    protocol: smtps
    host: smtppro.zoho.com
    username: bampo-noreply@yukinoeva7.com
    password: ${env.SPRING_MAIL_PASSWORD}
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtps:
          auth: true
          timeout: 50000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        debug: true